name: Daily Weather Script Automation

on:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 10 AM UTC
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  run-weather-script:
    runs-on: ubuntu-latest  # Running on the latest Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Install dependencies (if needed)
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq  # Install curl and jq if they are required for your script

      - name: Run the weather.sh script
        run: |
          bash ./weather.sh  # Assuming your script is in the root directory

      - name: Commit and push new data (if any)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub
        run: |
          git add .  # Add any new files or changes from the script
          git diff --cached --exit-code || git commit -m "Update weather data"
          git push

