name: Daily Script Execution

on:
  # Run the script at 10 AM every day
  schedule:
    - cron: '0 10 * * *'

  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Run the script
      run: |
        # Add your script execution command here
        echo "Running script..."
        # Example script execution, replace with your actual script
        ./your-script.sh
