name: Weather Script Automation

on:
  # Manually trigger the workflow
  workflow_dispatch:

  # Automatically run the script daily at 10 AM UTC
  schedule:
    - cron: '0 10 * * *'  # This means 10 AM every day (UTC time)

jobs:
  run_weather_script:
    runs-on: ubuntu-latest  # You can adjust the OS to your needs (ubuntu-latest is fine)

    permissions:
      # This allows the workflow to commit and push changes if needed
      contents: write  # Needed for committing and pushing changes to the repository
      actions: read  # Needed to allow action interaction, like dispatching workflows or job actions

    steps:
      # Checkout the repository to access the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up any environment (if your script needs specific software)
      - name: Set up environment
        run: |
          # For example, if the script needs curl or other utilities, you can install them here
          sudo apt-get update
          sudo apt-get install -y curl  # Add any dependencies you need for weather.sh

      # Make weather.sh script executable
      - name: Make weather.sh executable
        run: chmod +x ./weather.sh

      # Run the weather.sh script
      - name: Run weather.sh
        run: ./weather.sh

      # Commit and push changes (if the script modifies files and you want to commit those changes)
      - name: Commit and Push changes (if applicable)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated commit from weather.sh script execution"
          git push
        # This step will only execute if there are changes that need to be committed and pushed

